#include <stdio.h>

/**
 * main - Entry point
 *
 * Description: Each new term in the Fibonacci sequence
 * is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms
 * will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed 4,000,000, write a program
 * that finds and prints the sum of the even-valued terms,
 * followed by a new line.
 *
 * The numbers must be separated by comma, followed by a space ,
 * You are allowed to use the standard library
 *
 * Return: 0
 */

int main(void)
{
	int x;
	unsigned long y, z, sum, next;

	y = 1;
	z = 2;
	sum = 0;

	for (x = 0; x <= 32; x++)
	{
		if (sum < 4000000 && (y % 2) == 0)
		{
			sum += y;
		}

		next = y + z;
		y = z;
		z = next;
	}

	printf("%lu\n", sum);
	return (0);
}
